#define kMVNotificationSyncDidStart @"kMVNotificationSyncDidStart"
#define kMVNotificationSyncDidProgress @"kMVNotificationSyncDidProgress"
#define kMVNotificationSyncDidFinish @"kMVNotificationSyncDidFinish"